import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
const root = path.dirname(fileURLToPath(import.meta.url));
process.chdir(root);
await writeFile("app.js", await readFile("runtime.mjs", "utf8"));
const result = await postcss([tailwind({base:root})]).process(await readFile("app/globals.css","utf8"),{from:path.join(root,"app/globals.css"),to:path.join(root,"styles.css")});
await writeFile("styles.css",result.css+"\n"+await readFile("app/cinema.css","utf8"));
console.log("Copied runtime.mjs to app.js and rebuilt styles.css.");
